# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000ms
  keepAliveTimeout: 100000ms
  servlet:
    context-path: /e_gifts_web


spring:
  # 环境 dev|test|prod
  profiles:
    active: test
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true

# 基础路径
home :
  path: 'C:/EGIFTS' # 服务器真实路径

# 日志输出地址
logging:
  config: 'classpath:logback-spring.xml'
  path: '${home.path}/mylogs/web'

#mybatis
mybatis-plus:
  master:
    mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.bayer.process.*.entity
#  customizable-pagination-interceptor:
#    count-field: 'COUNT(1)'   # 自定义 select countField from (xx) 的countField默认内容, 默认为 'COUNT(1)'
#    count-field-alias: 'total' # 自定义 select countField AS countFieldAlias from (xx) countFieldAlias 内容, 默认为 'total'
#    use-mapper-count-sql: true  # 开启对同mapper中 总记录查询语句的<select>字句的使用, 默认为 false
#    count-sql-suffix: '_COUNT' # 选择使用什么后缀的同id<select>子句作为总记录数查询sql, 默认为'_COUNT'
#    max-limit: 2000  # 自定义一页最多有多少条记录数

  global-config:
    #数据库相关配置
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    